name: Go Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20
        cache: false

    - name: Проверить версию Go
      run: go version

    - name: Показать переменные окружения
      run: |
        echo $PATH
        which go

    - name: Install dependencies
      run: go mod tidy || echo "Нет зависимостей для установки"

    - name: Run build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...